Moved Envoys.reload to async
Artillex-Studios/AxEnvoys pull request #8
Opened 2024-08-01 10:55 UTC by WaterArchery

SlimeWorldManager loads and unloads worlds lots of times. So, using io operations halts the few server ticks. To prevent that, I moved the reload function to async.

2024-08-01 11:25 UTC, AverageGithub requested changes
Thank you for your contribution! I requested a change that should be pretty easy to resolve!

2024-08-01 11:25 UTC, AverageGithub commented on src/main/java/com/artillexstudios/axenvoy/envoy/Envoys.java
> +        }.runTaskAsynchronously(AxEnvoyPlugin.getInstance());
This approach won't cut it, as we support Folia. Use the Scheduler.get().runAsync(Runnable) method.

2024-08-01 19:33 UTC, WaterArchery commented
I implemented your change request.

2024-08-03 09:40 UTC, AverageGithub approved these changes
Thank you for your contribution!

2024-08-03 09:40 UTC, merged